spring.application.name=SpringMVC_2BookList
spring.datasource.username=root
spring.datasource.password=deepak1234B60
spring.datasource.url=jdbc:mysql://localhost:3306/bookusingdatajpa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
